### ISSUE TITLE
Readme file info about find/save and find/del pattern inaccurate

### ISSUE THREAD

**Issue by egoossens** [nolanlawson/relational-pouch#34]
Forgive me if I missed something, but it seems I can't reproduce the find/save and find/del patterns described in the Readme file.
The find method returns a collection object even when specifying an id. Shouldn't the first item be extracted before it can be fed to the del/save method?

```javascript
db.rel.find('post', 1).then(function (post) {
  return db.rel.del('post', post.posts[0]).catch(function (err) {
    if (err.code === 409) { // conflict
      // handle the conflict
    } else {
      throw err; // some other error
    }
  });
});
```

**Comment by nolanlawson** [comment]
You're right; that's a typo. :) Can you open a PR on the readme?
