### ISSUE TITLE
Support to bulk operations

### ISSUE THREAD

**Issue by repolitica** [nolanlawson/relational-pouch#43]
First of all, sorry for the inconvenience because I really dont know if this is an issue or an architecture decision not to offer bulk operations.

I am currently working with a large amount of documents and I found useful to keep the bulkDocs method supported by PouchDB. Why not exposing bulk save and bulk delete methods as described below?

``` javascript
  function _bulkSave(type, objs) {
    var typeInfo = getTypeInfo(type);
    var pouchDocs;
    return Promise.resolve().then(function () {
      pouchDocs = objs.map(function (obj) {
        return toRawDoc(typeInfo, obj);
      });
      return db.bulkDocs(pouchDocs);
    }).then(function (pouchRes) {
      var res = {};
      res[typeInfo.plural] = objs.map(function (obj, i) {
        return extend(true, obj, {
          id: deserialize(pouchRes[i].id),
          rev: pouchRes[i].rev
        });
      });
      return res;
    });
  }

  function _bulkDel(type, objs) {
    var typeInfo = getTypeInfo(type);
    var pouchDocs;
    return Promise.resolve().then(function () {
      pouchDocs = objs.map(function (obj) {
        var pouchDoc = toRawDoc(typeInfo, obj);
        return {
          _id: pouchDoc._id,
          _rev: pouchDoc._rev,
          _deleted: true
        };
      });
      return db.bulkDocs(pouchDocs);
    }).then(function () {
      return objs.map(function () {
        return {deleted: true};
      });
    });
  }

  function bulkSave(type, objs) {
    return Promise.resolve().then(function () {
      return _bulkSave(type, objs);
    });
  }

  function bulkDel(type, objs) {
    return Promise.resolve().then(function () {
      return _bulkDel(type, objs);
    });
  }

  db.rel = {
    bulkSave: bulkSave,
    bulkDel: bulkDel
  };
```

Also, I did some changes to ember-pouch adapter so it could use these bulk operations and accelerate insertions and deletions for large amount of data.

Thanks

**Comment by nolanlawson** [comment]
Yeah, I basically didn't support it because it didn't seem to be in the Ember Data API anywhere. But I'd be happy to add it if Ember Data comes up with a standard for it. :)

**Comment by meeximum** [comment]
Is there another way to check when PouchDB has saved all docs? I use a for loop to save my docs, and I want to react when all docs are really saved?

**Comment by broerse** [comment]
@meeximum Don't know if this will help but in `Paused` state all docs are saved. See https://github.com/broerse/ember-cli-blog/blob/master/app/adapters/application.js#L45

It will even detect that your WiFi is down. See the red en green clouds in this exmple: https://bloggr.exmer.com/

**Comment by meeximum** [comment]
@broerse thx, but I don't use the replication mechanism, I just use PouchDB as local storage for an Ionic2 app.
I tried around with the Promise.all(), I thought I can add every db.rel.save() statement to an array and then make a Promise.all() call, but the db.rel.save() functions didn't get resolved :-(

**Comment by meeximum** [comment]
ok it worked
```
let promises = new Array();
for (let customer of data.Customers) {
    promises.push(this._db.rel.save('customer', customer));
}

for (let holzart of data.Holzarten) {
    promises.push(this._db.rel.save('holzarten', holzart));
}
return Promise.all(promises);
```

**Comment by sahiliotasol** [comment]
Thanks @meeximum  You saved my day :)
