### ISSUE TITLE
PouchDB v5.4.5

### ISSUE THREAD

**Issue by aexmachina** [nolanlawson/relational-pouch#57]
I get an exception `Cannot read property 'Promise' of undefined` from pouch-utils.js when I upgrade to the latest version of PouchDB:

```
Promise = window.PouchDB.utils.Promise
```

**Comment by nolanlawson** [comment]
Sorry yeah, `PouchDB.utils` was removed and this project still mistakenly contains references to it.

**Comment by aexmachina** [comment]
Awesome thanks, I'll see if that fixes it and close this issue if so.

**Comment by nolanlawson** [comment]
1.4.4 is published and contains the fix. thanks for reporting!
