### ISSUE TITLE
Explanation about docID

### ISSUE THREAD

**Issue by akofman** [nolanlawson/relational-pouch#60]
Hello,

It's more a question than an issue. I'd just like to understand what the meaning of the number between underscores when creating a DocID : 
```
db.rel.makeDocID({ "type": "author", "id": 19 });
Returns:
"author_1_0000000000000019"
```
What the meaning of 1 ?

Thanks a lot.

**Comment by ramonsan** [comment]
Is the type of _id_ you are using. 

If you use a numeric one, relational id will be like "author_**1**_0000000000000019".

If you use a string one, relational id will be like "author_**2**_14760983-285C-6D1F-9813-D82E08F1AC29"

**Comment by akofman** [comment]
Aaaah ! It makes sense, thanks !
