### ISSUE TITLE
How do I do sort on the relational data

### ISSUE THREAD

**Issue by windmaomao** [nolanlawson/relational-pouch#66]
Just curious what is the best way to support sorting ? ex. I have multiple comments on a blog, but when I find this blog, I'd like comments to be sorted by timestamp, how do I do this ? Thanks.

**Comment by nolanlawson** [comment]
You would have to sort in-memory because relational-pouch itself offers no way to do this. Also even if it did, it would just do it in-memory anyway so there's no benefit relative to doing the sorting yourself in JavaScript code. Hope that helps!
