### ISSUE TITLE
Navigation properties on returned entity

### ISSUE THREAD

**Issue by webnoob** [nolanlawson/relational-pouch#71]
Hi,

I'd like to do something like: `customer.customersource.name`. Is this possible?

I know when I do `db.rel.find('customer', 'my_id')` it will return the customer *and* the related entities but it would be nice if it could also attach a property to the model for navigation purposes.

**Comment by nolanlawson** [comment]
Sorry, I'm not sure if I understand this request... if you'd like to attach custom properties to JS objects I believe you can do that yourself in user code?

**Comment by webnoob** [comment]
Yes of course and that is what I'm doing, it would just be nice to be able to have auto populated navigation properties (much in the same way a lazy loaded navigation property would work in Entity Framework for .NET).

Not an issue but thought I'd see if it existed.
